import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registery";
import Header from "./layouts/header";
import GlobalStyle from "./global-style";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body>
                <StyledComponentsRegistry>
                    <GlobalStyle>
                        <Header />
                        {children}
                    </GlobalStyle>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
